DROP DATABASE IF EXISTS craigilist;

CREATE DATABASE craigilist;

\c craigilist

CREATE TABLE Post
(
  id SERIAL PRIMARY KEY, 
  title TEXT NOT NULL,
  content TEXT NOT NULL,
  user INTEGER NOT NULL REFERENCES User,
  location TEXT NOT NULL,
  region INTEGER NOT NULL REFERENCES Region,
  category INTEGER NOT NULL REFERENCES Category
);

CREATE TABLE Category
(
  id SERIAL PRIMARY KEY, 
  name TEXT NOT NULL
);

CREATE TABLE User
(
  id SERIAL PRIMARY KEY, 
  name TEXT NOT NULL
);

CREATE TABLE Region
(
  id SERIAL PRIMARY KEY, 
  name TEXT NOT NULL
);

